<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.uiautomation.Tests.verifyhoteltestEqualExperts" tests="1" time="8.522" ignored="0" failures="1" timestamp="25 Jan 2020 15:24:18 GMT" skipped="0" hostname="DESKTOP-NOTMME9" errors="0">
  <testcase name="TS01_VerifyHotelBookingFormWithValidCredentials" time="8.522" classname="com.uiautomation.Tests.verifyhoteltestEqualExperts">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Check-out] but found [Stephen TVST],
	expected [Deposit] but found [904]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Check-out] but found [Stephen TVST],
	expected [Deposit] but found [904]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.uiautomation.basePage.TestBase.assertAll(TestBase.java:113)
	at com.uiautomation.Tests.verifyhoteltestEqualExperts.TS01_VerifyHotelBookingFormWithValidCredentials(verifyhoteltestEqualExperts.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TS01_VerifyHotelBookingFormWithValidCredentials -->
</testsuite> <!-- com.uiautomation.Tests.verifyhoteltestEqualExperts -->
